### ISSUE TITLE
Error when deserializing tfrecord's in TF 2.x: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices

### ISSUE THREAD

**Issue by dgoldenberg-audiomack** [linkedin/spark-tfrecord#19]
The lib doesn't seem to be working in the context of TensorFlow 2.x.

My environment:
- AWS emr-5.31.0
- TF=2.1.0, Spark=3.0.1
- built the spark-tfrecord library using the command: `mvn -Pscala-2.12 clean install -Dspark.version=3.0.1 -Dtensorflow.hadoop.version=1.15.0` (1.15.0 is the latest in maven central currently)
- tried with recordType=Example and recordType=SequenceExample, get the same error

The reading and the writing do not match.  After persisting into AWS S3, I see that the serde is somehow mismatched, perhaps it's doing a TF 1.x compatible stuff and not TF 2.x ?

To reproduce:
- execute in Spark, with --jars s3://<your jars location>/spark-tfrecord_2.12-0.3.0.jar
- use a Bootstrap action in EMR to get boto3 installed on the cluster; this worked for me:
```
#!/bin/bash
pip3 install --user boto3
```
- the python tester program is attached
- I used the small movielens dataset (see the attached movies.csv and ratings.csv)

```
>> Ratings: <class 'tensorflow.python.data.ops.readers.TFRecordDatasetV2'>; size=100004
>> Movies: <class 'tensorflow.python.data.ops.readers.TFRecordDatasetV2'>; size=9125

TFRecordDatasetV2 does not appear to load/deserialize the tfrecords persisted by spark-tfrecord_2.12-0.3.0.jar:

********************************************************************************
(b'\ns\n\x11\n\x08movie_id\x12\x05\x1a\x03\n\x01\x01\n#\n\x0bmovie_title'
 b'\x12\x14\n\x12\n\x10Toy Story (1995)\n9\n\x06genres\x12/\n-\n+Adventure|Anim'
 b'ation|Children|Comedy|Fantasy\x12\x00')
********************************************************************************

(b'\n|\n\x10\n\x07user_id\x12\x05\x1a\x03\n\x01\x01\n\x11\n\x08movie_id'
 b'\x12\x05\x1a\x03\n\x01\x1f\n)\n\x0bmovie_title\x12\x1a\n\x18\n\x16Dangerou'
 b's Minds (1995)\n\x12\n\x06rating\x12\x08\x12\x06\n\x04\x00\x00 @\n\x16\n\tti'
 b'mestamp\x12\t\x1a\x07\n\x05\xe8\xd0\x96\xd9\x04\x12\x00')
********************************************************************************
```

The error when running in the cluster:

> Traceback (most recent call last):
  File "/mnt/tmp/spark-9eb04118-c94f-4ed6-bb6b-75927f4d389f/recsys_tfrs_proto.py", line 304, in <module>
    main(sys.argv)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/mnt/tmp/spark-9eb04118-c94f-4ed6-bb6b-75927f4d389f/recsys_tfrs_proto.py", line 50, in main
    movies, test, train, unique_movie_titles, unique_user_ids = prepare_data(movies, ratings)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/mnt/tmp/spark-9eb04118-c94f-4ed6-bb6b-75927f4d389f/recsys_tfrs_proto.py", line 155, in prepare_data
    ratings = ratings.map(lambda x: {"movie_title": x["movie_title"], "user_id": x["user_id"]})
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1695, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4045, in __init__
    use_legacy_function=use_legacy_function)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3371, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/eager/function.py", line 2939, in get_concrete_function
    *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/eager/function.py", line 2906, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3364, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3299, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/mnt/tmp/spark-9eb04118-c94f-4ed6-bb6b-75927f4d389f/recsys_tfrs_proto.py", line 155, in <lambda>
    ratings = ratings.map(lambda x: {"movie_title": x["movie_title"], "user_id": x["user_id"]})
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 986, in _slice_helper
    _check_index(s)
  File "/usr/local/lib64/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 865, in _check_index
    raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got 'movie_title'

[spark-tfrecord-serde-issue.zip](https://github.com/linkedin/spark-tfrecord/files/5748399/spark-tfrecord-serde-issue.zip)

**Comment by junshi15** [comment]
Did this work in TF1, in case you tested it already?

**Comment by junshi15** [comment]
In your code, you did the following:

1. Read the movies and ratings CSV files. (Spark)
2. Join movies with ratings. (Spark)
3. Save movies and ratings in TFRecord format. (Spark-TFRecord)
4. Read back movies and ratings with tf.data.TFRecordDataset. (Tensorflow 2.1.0)
Can you confirm this is what you tried to do?

**Comment by dgoldenberg-audiomack** [comment]
@junshi15 Hi, thanks for looking into this.

I have not tested in TF1; it would take me a while to set that kind of environment correctly; I am on TF 2.x.

As far as the steps, yes, you're exactly right, that is what I'm doing.

Please note that the following line of code is wrong:
```
ratings.map(lambda x: {"movie_title": x["movie_title"], "user_id": x["user_id"]})
```
That's a copy and paste from a tutorial where the dataset is loaded from tensorflow datasets using the `load` method. Since the record is of type `class bytes`, the map operation will fail.

I've rewritten the code to be more to the point (see attached). I don't see the `Only integers, slices...` error anymore. However, TFRecordDataset is not loading from S3 filepaths.  I would think since I'm able to write to S3, I should be able to load from there with no issues.

Here's the stack; code is attached as well.

> Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2113, in execution_mode
    yield
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 733, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2579, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unknown: : curlCode: 77, Problem with the SSL CA cert (path? access rights?) [Op:IteratorGetNext]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/mnt/tmp/spark-86dec8a4-40fa-4929-af2b-2f1345448837/recsys_tfrs_proto.py", line 128, in <module>
    main(sys.argv)
  File "/mnt/tmp/spark-86dec8a4-40fa-4929-af2b-2f1345448837/recsys_tfrs_proto.py", line 123, in main
    test_conversion(spark)
  File "/mnt/tmp/spark-86dec8a4-40fa-4929-af2b-2f1345448837/recsys_tfrs_proto.py", line 98, in test_conversion
    for el in movies_dataset.take(1).as_numpy_iterator():
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3942, in __next__
    return nest.map_structure(lambda x: x.numpy(), next(self._iterator))
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 747, in __next__
    return self._next_internal()
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 739, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib64/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2116, in execution_mode
    executor_new.wait()
  File "/home/hadoop/.local/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 69, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unknown: : curlCode: 77, Problem with the SSL CA cert (path? access rights?)

[spark_tfrecord_issue_19.py.zip](https://github.com/linkedin/spark-tfrecord/files/5752685/spark_tfrecord_issue_19.py.zip)

**Comment by junshi15** [comment]
I did a quick test on my local machine, by reading movise.csv, writing it in TFRecord, then reading/parsing in Tensorflow. I don't see problems. See the snippet below: 

```python
# ===================================
# run the following in pyspark shell.
# this is how I launched it.
# spark-3.0.0-bin-hadoop2.7/bin/pyspark --packages com.linkedin.sparktfrecord:spark-tfrecord_2.12:0.3.0
# ===================================

input_file = 'movies.csv'
output_path = 'movies_tfrecord'

df = spark.read.option("header",True).csv(input_file)
df.write.mode("overwrite").format("tfrecord").option("recordType", "Example").save(output_path)


# ====================================
# run the following with tensorflow 2.3
# ====================================
import tensorflow as tf

files = tf.io.gfile.glob(f'{output_path}/*.tfrecord')

def map_fn(serialized):
    features={'movieId': tf.io.FixedLenFeature([], tf.string),
              'title': tf.io.FixedLenFeature([], tf.string),
              'genres': tf.io.FixedLenFeature([], tf.string)}
    return tf.io.parse_example(serialized, features)


dataset = tf.data.TFRecordDataset(files).map(map_fn)
for i, e in enumerate(dataset):
    if i >= 5:
        break
    print(e)

# ====================================
# I got the following output, it looks reasonable to me.
# {'genres': <tf.Tensor: shape=(), dtype=string, numpy=b'Adventure|Animation|Children|Comedy|Fantasy'>, 'movieId': <tf.Tensor: shape=(), dtype=string, numpy=b'1'>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Toy Story (1995)'>}
# {'genres': <tf.Tensor: shape=(), dtype=string, numpy=b'Adventure|Children|Fantasy'>, 'movieId': <tf.Tensor: shape=(), dtype=string, numpy=b'2'>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Jumanji (1995)'>}
# {'genres': <tf.Tensor: shape=(), dtype=string, numpy=b'Comedy|Romance'>, 'movieId': <tf.Tensor: shape=(), dtype=string, numpy=b'3'>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Grumpier Old Men (1995)'>}
# {'genres': <tf.Tensor: shape=(), dtype=string, numpy=b'Comedy|Drama|Romance'>, 'movieId': <tf.Tensor: shape=(), dtype=string, numpy=b'4'>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Waiting to Exhale (1995)'>}
# {'genres': <tf.Tensor: shape=(), dtype=string, numpy=b'Comedy'>, 'movieId': <tf.Tensor: shape=(), dtype=string, numpy=b'5'>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Father of the Bride Part II (1995)'>}
# ====================================
```

**Comment by dgoldenberg-audiomack** [comment]
Yeah I'm missing that last step, the `map_fn` type of parsing

**Comment by junshi15** [comment]
Close the issue since the generated TFRecord file can be parsed in TF2.3 as shown in the example above.
