### ISSUE TITLE
Does not support Nested ArrayTypes

### ISSUE THREAD

**Issue by apurva-sharma** [linkedin/spark-tfrecord#70]
Hello,

I am essentially trying to write a tfrecord which i hope to serialize into Sparse Tensors.
To that end, I have a dataframe that looks like this:

```
|num_features|indices                                                       |values                                              |
+------------+--------------------------------------------------------------+----------------------------------------------------+
|1056        |[[0]]                                                         |[1.0]                                               |
|1056        |[[1]]                                                         |[1.0]                                               |
|1056        |[[0]]                                                         |[1.0]                                               |
|1056        |[[0]]                                                         |[1.0]                                               |
|1056        |[[1], [56], [57], [59], [61], [66], [72], [102], [180], [194]]|[1.0, 38.0, 8.0, 3.0, 1.0, 20.0, 1.0, 2.0, 2.0, 7.0]|
```

Writing this as an example throws:
Caused by: java.lang.ClassCastException: com.linkedin.spark.shaded.org.tensorflow.example.FeatureList cannot be cast to com.linkedin.spark.shaded.org.tensorflow.example.Feature
	at com.linkedin.spark.datasources.tfrecord.TFRecordSerializer.$anonfun$serializeExample$1(TFRecordSerializer.scala:22)
	at com.linkedin.spark.datasources.tfrecord.TFRecordSerializer.$anonfun$serializeExample$1$adapted(TFRecordSerializer.scala:19)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at com.linkedin.spark.datasources.tfrecord.TFRecordSerializer.serializeExample(TFRecordSerializer.scala:19)
	at com.linkedin.spark.datasources.tfrecord.TFRecordOutputWriter.write(TFRecordOutputWriter.scala:29)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.write(FileFormatDataWriter.scala:175)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:85)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:403)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
	... 17 more

The problematic column is indices (of form ArrayType(ArrayType(IntegerType()))
If I instead represent indices as ArrayType(IntegerType()) (i.e. [1, 56, 57]....) in the example above, then the writes are fine.

**Comment by catdollar** [comment]
Try `sequenceExample` for nested array.

**Comment by apurva-sharma** [comment]
this worked fine, thanks for the quick guidance!
