### ISSUE TITLE
spark-tfrecord writes not working for spark 3.5.0

### ISSUE THREAD

**Issue by lzuwei** [linkedin/spark-tfrecord#72]
Hi @junshi15 , thanks for maintaining this library to simplify tfrecord support for spark.

We recently tried to update our spark version to 3.5.0 and it seems that there are some changes in this new version that breaks this library (0.7.0).

When trying to save our spark dataframe to tfrecord using this library we are encountering the following errors:

```
java.lang.AbstractMethodError: Receiver class com.linkedin.spark.datasources.tfrecord.TFRecordOutputWriter does not define or inherit an implementation of the resolved method 'abstract java.lang.String path()' of abstract class org.apache.spark.sql.execution.datasources.OutputWriter.
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.$anonfun$write$2(FileFormatDataWriter.scala:176)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.$anonfun$write$2$adapted(FileFormatDataWriter.scala:176)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.write(FileFormatDataWriter.scala:176)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:85)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:403)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:410)
	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
...
```

Here is a minimal example (python) to reproduce the error:
```
from pyspark import SparkConf, SparkContext
from pyspark.sql import SparkSession, DataFrame
from pyspark.sql.types import *

conf = (SparkConf()
        .set("spark.jars.packages", "com.linkedin.sparktfrecord:spark-tfrecord_2.12:0.7.0")
        .setAppName("test-case")
        )

spark = SparkSession.builder.master("local[1]").appName("test-tfrecord").config(conf=conf).getOrCreate()
path = "test-output.tfrecord"

fields = [StructField("id", IntegerType()), StructField("IntegerCol", IntegerType()),
          StructField("LongCol", LongType()), StructField("FloatCol", FloatType()),
          StructField("DoubleCol", DoubleType()), StructField("VectorCol", ArrayType(DoubleType(), True)),
          StructField("StringCol", StringType())]
schema = StructType(fields)
test_rows = [[11, 1, 23, 10.0, 14.0, [1.0, 2.0], "r1"], [21, 2, 24, 12.0, 15.0, [2.0, 2.0], "r2"]]
rdd = spark.sparkContext.parallelize(test_rows)
df_test = spark.createDataFrame(rdd, schema)
df_test.write.mode("overwrite").format("tfrecord").option("recordType", "Example").save(path)
```

Any advice or insights to this issue is greatly appreciated!

**Comment by junshi15** [comment]
It worked for me. I tested with pyspark shell.
```
./pyspark --packages com.linkedin.sparktfrecord:spark-tfrecord_2.12:0.7.0
```
ran your code, except the config and SparkSession lines.

**Comment by lzuwei** [comment]
Thank you for checking, can I check your environment to cross compare against ours.
Eg: spark version, jdk version.

**Comment by junshi15** [comment]
spark 3.5.0
python 3.10.9
openjdk "1.8.0_362" (this probably did not matter)

**Comment by lzuwei** [comment]
Thank you for the information, I have identified the issue. It seems that our environment somehow did not remove the older version of spark-tfrecord which is not compatible with spark 3.5.0, as a result the runtime loaded the wrong jar. Removing the incompatible version fixes the issue.

Closing the issue.
